.PHONY: test security run stop

RABBIT_MQ_QUEUE="q-mailer"
RABBIT_MQ_DIAL="amqp://guest:guest@localhost:15672/"
SMTP_HOST="smtp.gmail.com"
SMTP_PORT=587
SMTP_EMAIL_ADDRESS="cointrade.exchg@gmail.com"
SMTP_EMAIL_PASSWORD="fecdaj-sensu9-Devtoc"

BUILD_DIR = $(PWD)/app

security:
	gosec -quiet ./...

test: security
	go test -v -timeout 30s -coverprofile=cover.out -cover ./...
	go tool cover -func=cover.out

docker_build_image:
	docker build -t cooljar-go-mailer-service .

docker_app: docker_build_image
	docker container run -d \
        	--name cooljar-go-mailer-service-c \
            -e RABBIT_MQ_DIAL=$(RABBIT_MQ_DIAL) \
            -e RABBIT_MQ_QUEUE=$(RABBIT_MQ_QUEUE) \
            -e SMTP_HOST=$(SMTP_HOST) \
            -e SMTP_PORT=$(SMTP_PORT) \
            -e SMTP_EMAIL_ADDRESS=$(SMTP_EMAIL_ADDRESS) \
            -e SMTP_EMAIL_PASSWORD=$(SMTP_EMAIL_PASSWORD) \
            cooljar-go-mailer-service
	docker container start cooljar-go-mailer-service-c

run: docker_app

stop:
	docker container stop cooljar-go-mailer-service-c
	docker container rm cooljar-go-mailer-service-c
	docker rmi cooljar-go-mailer-service
